name: Run Interior Design Agent Initializer

on:
  push:
    branches:
      - main
    paths:
      - 'src/app/agents/interiorDesignAgent_initializer.py'
      - 'src/prompts/InteriorDesignAgentPrompt.txt'
      - 'src/app/tools/imageCreationTool.py'
      - 'src/app/tools/aiSearchTools.py'
      - 'src/app/agents/agent_processor.py'
      - 'src/app/agents/agent_initializer.py'
  workflow_dispatch:

jobs:
  run-agent-initializer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r src/requirements.txt

      - name: Create .env file from secret
        run: echo "$ENV" > src/.env
        shell: bash
        env:
          ENV: ${{ secrets.ENV }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Run Interior Design Agent Initializer
        working-directory: src/app/agents
        run: python interiorDesignAgent_initializer.py
